### ISSUE TITLE
Project Images On Homepage Scale Proportionally

### ISSUE THREAD

**Issue by kieranstartup** [blerchin/bfamfaphd-website#15]
Scale the project images proportionally instead of having them shrink down to a square

**Comment by blerchin** [comment]
not totally sure if I understand what you have in mind. Seems like this contradicts https://github.com/blerchin/bfamfaphd-website/issues/16

For now I've changed to a landscape-oriented container and set it as `background-size: cover;` which should be more flexible.

**Comment by carolinewoolard** [comment]
I agree Ben, seems fine
