### ISSUE TITLE
pixel polish: the background color should be 10% of the color in the card

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#37]
right now, the background color in each phase of the supply chain (see source) is not legible. it's so nice to draw from the card, but please make it 10% of the color on the card, not 100%. this will make it legible. Please make the text black, not blue.

**Comment by e-milio** [comment]
![screen shot 2016-07-26 at 5 03 46 pm](https://cloud.githubusercontent.com/assets/8782080/17155411/f6468bf4-5352-11e6-95ce-37868536d0e0.png)
