### ISSUE TITLE
bug: make past events / exhibitions / workshops on another page

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#40]
For more beautiful / clear viewing, can you make a page http://bfamfaphd.com/#topic-events/past so that I don't see ALL past events on the homepage? This can happen in August if need be. Remember we talked about past events automatically going to a "past" area, like on my website? http://carolinewoolard.com/past-events/ vs. http://carolinewoolard.com/#events/

Also, I don't think we need lines between all the kinds of past events (workshops, lectures, etc.) they can all be PAST events or just remove those lines...

![screen shot 2016-08-05 at 4 05 31 pm](https://cloud.githubusercontent.com/assets/925548/17449162/c9e7b944-5b26-11e6-87e8-1b907be9486e.png)

![screen shot 2016-07-28 at 12 29 04 pm](https://cloud.githubusercontent.com/assets/925548/17220840/15d4baaa-54bf-11e6-84cb-e2fa895c70d3.png)
![screen shot 2016-07-28 at 12 29 15 pm](https://cloud.githubusercontent.com/assets/925548/17220841/15d4fbaa-54bf-11e6-9fe2-80be0d15faff.png)

**Comment by blerchin** [comment]
Totally do-able, and events /do/ automatically move from 'Upcoming' to 'Past Workshops' or 'Past Discussion' based on the category they are assigned on creation.

Going to leave this as low priority for now & focus on Supply chain issues first (there are a lot, I know.)
