### ISSUE TITLE
pixel polish: the width of the text should expand when the window expands 

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#43]
As I make my browser smaller, the images snap to the right (they should be centered) and the text feels alone in a huge field of pink and white. This site should allow the width of the text to change as the window expands... and have more text per line when I see it on a laptop vs ipad vs phone. The phone dimensions look good, but the laptop is off. The fields of color look very weird without anything on the right -- it's as though we are about to serve ads on that side. If that's not possible, make the pink field the dimension for a phone and allow the rest of the site to be white. Call me if this is too confusing.

![screen shot 2016-07-30 at 7 59 20 am](https://cloud.githubusercontent.com/assets/925548/17270222/0bcbcb98-562c-11e6-8c81-3f46f7b63c90.png)
![screen shot 2016-07-30 at 7 59 28 am](https://cloud.githubusercontent.com/assets/925548/17270223/0bcd54c2-562c-11e6-92c2-75a479932f38.png)
![screen shot 2016-07-30 at 7 59 43 am](https://cloud.githubusercontent.com/assets/925548/17270224/0bcff948-562c-11e6-8b5a-5d2cbe03d587.png)

**Comment by blerchin** [comment]
This is much better in the latest push. Let me know if you think it's ready to roll.

**Comment by carolinewoolard** [comment]
good --- yeah close it

On Wed, Aug 3, 2016 2:29 AM, blerchin notifications@github.com wrote:
This is much better in the latest push. Let me know if you think it's ready to
roll.
