### ISSUE TITLE
pixel polish: the About header disappeared!

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#50]
When I edited "About" the header went away. Can it be there, like Art is, looking so nice?

![screen shot 2016-08-05 at 3 37 39 pm](https://cloud.githubusercontent.com/assets/925548/17448616/457084be-5b23-11e6-8dc1-797ebef3aa18.png)

**Comment by blerchin** [comment]
Headers are added inline, to allow for Sub-headings at the same level of heirarchy.

you can add `<h4>About</h4>` at the top of the article and it will come back
