### ISSUE TITLE
bug: disable supply chains!!! PRIORITY

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#57]
This is the major thing to do, please link to bfamfaphd.com/cards rather than the supply chains site, until that's done...
![screen shot 2016-08-08 at 7 24 56 am](https://cloud.githubusercontent.com/assets/925548/17478386/508c1af8-5d39-11e6-95f8-4ab09ffa9395.png)

**Comment by blerchin** [comment]
Fixed
