### ISSUE TITLE
pixel polish: tone down color or adjust color behind text copy

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#6]
While the color from the cards looks really nice, it is very hard to read with bright color backgrounds. Please make the color from the card only bright around the slideshow / card and then make the background where the text in each section is very light OR make each section entirely light, the color of the card with 5% opacity or something like that.
![screen shot 2016-06-02 at 7 25 09 am](https://cloud.githubusercontent.com/assets/925548/15743422/5a203f70-2893-11e6-88ec-4e1034c4276e.png)

**Comment by blerchin** [comment]
Same as https://github.com/blerchin/bfamfaphd-website/issues/37
