### ISSUE TITLE
Spread the Of Supply Chains menu items across the full width of the menu bar?

### ISSUE THREAD

**Issue by kieranstartup** [blerchin/bfamfaphd-website#64]
![screen shot 2016-08-17 at 18 00 00](https://cloud.githubusercontent.com/assets/5398966/17745622/753df8c2-64a4-11e6-89e4-3f8b6d64cfa9.png)
- Flexbox space between is the layout I'm imagining > [flexbox example](http://the-echoplex.net/flexyboxes/?fixed-height=on&display=flex&flex-direction=row&flex-wrap=wrap&justify-content=space-between&align-items=flex-start&align-content=stretch&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto)

**Comment by blerchin** [comment]
I tried this, but it ended up looking not-so-great. Flexbox divides the space into 12 equally spaced boxes, but the words are not equal width so spacing between them was inconsistent and visually distracting. Wish there was something like `text-align: justify;` for boxes, but to my knowledge this doesn't exist.
