### ISSUE TITLE
pixel polish: Increase type size for body text and headers, decrease padding

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#78]
Increase type size for body text and headers:

- everything should be bumped up +2 points, from 8 to 10 or from 9 to 11, etc. See the NYTimes website / phone for ideas of the right size). 

- make the headers bigger than the body text, so EVENTS is bigger than Upcoming Events, etc.

- You may need to extend the width of the body text throughout, as you have A LOT of padding on either side. On a phone, especially, I only see 4 words per line, when I should see 7 words per line.

![screen shot 2016-11-21 at 9 31 16 am](https://cloud.githubusercontent.com/assets/925548/20486389/82ba8b4a-afcd-11e6-9559-902003a0aae6.png)

**Comment by blerchin** [comment]
@carolinewoolard have addressed these with pretty extensive type improvements. Let me know if I missed anything.
