### ISSUE TITLE
pixel polish: separate "Intro" from "About"

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#79]
right now, the video is under "about" but then it jumps into the "intro" text for our book. We need to separate these two things. Please keep the video and add space for text that is a short "about." Then Events will go below that. Then the Intro to the book, with those sections.

![Uploading Screen Shot 2016-11-21 at 9.46.36 AM.png…]()

**Comment by blerchin** [comment]
Done.

In the Supply Chain page editor, note the `[supply_chain_section]` and `[/supply_chain_section]` tags which denote the start and end of each section. Title should always be outside of those tags, and all content should be inside. Feel free to add other sections if that would be helpful.
